#!/usr/bin/env python3
"""
build_universe.py — regenerates the scan universes from stocks.csv.

Both stock boards (trend/ and quiet/) scan the same list. That list used to be
the 752-name Nifty Total Market and was keyed on ticker; it is now every listed
company in `stocks.csv` that has a tradable listing, keyed on ISIN:

    INE002A01018,RELIANCE.NS

The ISIN is the identity the scanners carry through to their output; the Yahoo
symbol after the comma is only how the price is fetched.

Run after editing stocks.csv:  python build_universe.py
"""

import sys

import stock_registry as registry

TARGETS = ["trend/universe.txt", "quiet/universe.txt"]

HEADER = """\
# Scan universe — every listed company in ../stocks.csv with a tradable listing.
# Generated by build_universe.py; edit stocks.csv and re-run, not this file.
#
# One company per line:  <ISIN>,<Yahoo symbol>
#   ISIN         the identity carried into trend.json
#   Yahoo symbol how the price is fetched: SYMBOL.NS on NSE, CODE.BO for
#                BSE-only listings
#
# {n} companies ({nse} NSE, {bse} BSE-only). {skipped} companies in stocks.csv
# are listed on neither exchange and cannot be scanned.
"""


def main():
    rows = registry.load()
    scannable = registry.scannable(rows)
    scannable.sort(key=lambda r: r["yahoo"])

    body = "".join(f"{r['isin']},{r['yahoo']}\n" for r in scannable)
    head = HEADER.format(
        n=len(scannable),
        nse=sum(1 for r in scannable if r["yahoo"].endswith(".NS")),
        bse=sum(1 for r in scannable if r["yahoo"].endswith(".BO")),
        skipped=len(rows) - len(scannable),
    )

    for path in (sys.argv[1:] or TARGETS):
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(head + body)
        print(f"wrote {path} — {len(scannable)} companies")


if __name__ == "__main__":
    main()
